In [2]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]], dtype="int64")
print(array)
print(array.shape)  # 返回元组表示array的维度
print(array.ndim)  # 返回数字表示array维度的数目
print(array.size)  # 返回数字表示array中所有数据元素的数目

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6


In [4]:
print(np.empty((3, 4)))
print(np.linspace(1, 10, 5)) # 把1到10均匀地分成4段，共产生5个数

[[9.93209503e-312 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.03977794e-312 1.86489766e+160 3.79279783e+179 9.59401183e-043]
 [1.39555612e-047 7.46418646e-038 2.37941199e+184 5.69654234e-038]]
[ 1.    3.25  5.5   7.75 10.  ]


In [9]:
# np.tan(0.7854)*10  # 这里的0.7854是弧度制的
np.sin(np.pi/2)

1.0

In [4]:
a = np.array([[1, 2], [4, 5]])
b = np.arange(4).reshape((2, 2))
c = a*b  # 对应元素直接相乘
d_dot = np.dot(a, b)  # 矩阵乘法
d_dot_2 = a.dot(b)  # 矩阵乘法另一种形式
print(c)
print(d_dot)
print(d_dot_2)

[[ 0  2]
 [ 8 15]]
[[ 4  7]
 [10 19]]
[[ 4  7]
 [10 19]]


In [5]:
a = np.array([[0, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(np.sum(a, axis=1))
print(np.diff(a))  # 后一位元素减去前一位元素。因为一行5个数，只有前4个数有后一位元素，所以是2行4列
print(np.nonzero(a))  # 第一个array表示行，第二个array表示列，会返回所有非0元素的索引

[14 40]
[[2 1 1 1]
 [1 1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int64), array([1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))


In [6]:
a = np.array([[0, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a)
print(a.T)  # 矩阵转置
print(a.clip(5, 9))  # 比5小的都变为5，比9大的都变为9，5和9之间的不变

[[ 0  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 0  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[[5 5 5 5 5]
 [6 7 8 9 9]]


In [3]:
A = np.arange(3, 15).reshape(3, 4)
print(A)
print(A[[1, 2], [1, 2]])
print(A[1, 1:3])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 8 13]
[8 9]


In [11]:
a = np.arange(36).reshape(9, 4)
print(a)
print(a[[0, 1], [2, 3]])  # 0行2列 1行3列
b = np.array([[0, 1], [2, 3]])
c = np.array([0, 1, 2, 3])
print(f"二维数组用二维数组进行索引结果：\n{a[b]}")  # 二维数组用二维数组进行索引，返回三维数组。0行 1行  2行 3行
print(f"二维数组用一维数组进行索引结果：\n{a[c]}")
print(
    a.T[b]
)  # 将同样一个二维数组转置后用二维数组进行索引，返回三维数组。返回的是原二维数组的0列 1列  2列 3列

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]
[2 7]
二维数组用二维数组进行索引结果：
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
二维数组用一维数组进行索引结果：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[[ 0  4  8 12 16 20 24 28 32]
  [ 1  5  9 13 17 21 25 29 33]]

 [[ 2  6 10 14 18 22 26 30 34]
  [ 3  7 11 15 19 23 27 31 35]]]


In [14]:
a = np.arange(36).reshape(9, 4)
print(a)
print(a.flatten())  # 将一个多维数组转为一维数组，返回一个一维数组
print(a.flat)
for item in a.flat:  # 返回一个迭代器
    print(item)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35


In [10]:
# array合并
a = np.array([1, 1, 1])
b = np.array([2, 2, 2])
c = np.vstack((a, b, a))  # vertical stack:竖直方向合并
d = np.hstack((a, b))  # horizontal stack:水平方向合并
print(f"竖直合并结果:\n{c}")
print(f"水平合并结果:\n{d}")
e = a[:, np.newaxis]
f = b[:, np.newaxis]
print(f"转置后竖直合并结果:\n{np.vstack((e, f))}")
print(f"转置后水平合并结果:\n{np.hstack((e, f))}")
g = np.concatenate((e, f), axis=0)  # concatenate:可以用axis参数选择合并的方向
h = np.concatenate((e, f), axis=1)
print(g)
print(h)

竖直合并结果:
[[1 1 1]
 [2 2 2]
 [1 1 1]]
水平合并结果:
[1 1 1 2 2 2]
转置后竖直合并结果:
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
转置后水平合并结果:
[[1 2]
 [1 2]
 [1 2]]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
[[1 2]
 [1 2]
 [1 2]]


In [11]:
# 一维数组进行转置的方法
# ①reshape(-1,1)
a = np.array([1, 1, 1])
# numpy会根据数组的总元素数量以及其他指定维度的大小,来确定-1对应的维度大小。
# (-1,1)表示将所有元素排成一列,行数根据数组的总元素数量自动计算得出
print(f"一维数组转置:\n{a.reshape(-1, 1)}")
a = np.array([1, 1, 1, 2, 2, 2])
print(f"一维数组转为两列:\n{a.reshape(-1, 2)}")
# ②mat:接收多种输入（元组，列表，数组），将其转化为矩阵对象
b = np.mat(a)
print(b.T)
# ③newaxis:用于新增一个维度
# a.shape是(6,),a[:,np.newaxis].shape是(6, 1),a[np.newaxis,:].shape是(1,6)
# a[:,np.newaxis]在第1个位置插入1个维度，(6,)变为(6,1);a[np.newaxis,:]在第0个位置插入1个维度，(6,)变为(1,6)
print(a[:, np.newaxis], a[:, np.newaxis].shape)
print(a[np.newaxis, :], a[np.newaxis, :].shape)

一维数组转置:
[[1]
 [1]
 [1]]
一维数组转为两列:
[[1 1]
 [1 2]
 [2 2]]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]] (6, 1)
[[1 1 1 2 2 2]] (1, 6)


In [15]:
a = np.arange(12).reshape(3, 4)
b = a[0]
c = a[1:]
print(b[np.newaxis,:].T)
print(b[:,np.newaxis])
print(c)

[[0]
 [1]
 [2]
 [3]]
[[0]
 [1]
 [2]
 [3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
# array分割
a = np.arange(12).reshape(3, 4)
print(a)
print(np.split(a, 2, axis=1))  # split(数组,分割的份数,分割的方向)
# print(np.split(a,2,axis=0)) split必须进行等比例分割，如果不等比例会报错
print(np.array_split(a, 2, axis=0)) # 不等比例的分割可以用array_split
print(np.vsplit(a,3)) # 竖直方向分割
print(np.hsplit(a,4)) # 水平方向分割

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [20]:
a = np.arange(36).reshape((6, 6))
print(a)
print(a[[2, 2, 4, 4], [1, 3, 1, 3]])
# [[2, 2], [4, 4]]是行索引数组，[[1, 3], [1, 3]]是列索引数组，按位置对应提取元素
print(a[[[2, 2], [4, 4]], [[1, 3], [1, 3]]])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[13 15 25 27]
[[13 15]
 [25 27]]


In [22]:
import numpy as np
数组 = np.arange(36).reshape(9, 4)
print(数组)
print("*"*15)
print(数组[[4, 3, 0, 6]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]
***************
[[16 17 18 19]
 [12 13 14 15]
 [ 0  1  2  3]
 [24 25 26 27]]
